// userApi.js
import { createApi, fetchBaseQuery } from '@reduxjs/toolkit/query/react';

export const userApi = createApi({
  reducerPath: 'userApi',
  baseQuery: fetchBaseQuery({ baseUrl: 'http://localhost:8080/api/v1/auth' }),
  tagTypes: ['User'],
  endpoints: (builder) => ({
    
    // ---- SIGN UP ----
    signUp: builder.mutation({
      query: (userData) => ({
        url: '/mainSignUp',
        method: 'POST',
        body: userData,
      }),
    }),

    // ---- SIGN IN ----
    signIn: builder.mutation({
      query: (credentials) => ({
        url: '/mainSignIn',
        method: 'POST',
        body: credentials,
      }),
    }),
    
  }),
});

// ---- Export hooks automatically generated by RTK Query ----
export const { useSignUpMutation, useSignInMutation } = userApi;
